### ISSUE TITLE
Can't connect to my Philips TV

### ISSUE THREAD

**Issue by roman-rv** [ambilight-4-mediaportal/AtmoOrb#2]
Hi. Philips 55pft6510/60. Cant find hue bridge. Other UDP device in a home network work fine. Thanx.

**Comment by Lightning303** [comment]
AtmoOrb is not designed to connect/work with any TV, or with a Hue bridge. Its independant to Philips/Hue products. And is rather an alternative.

**Comment by roman-rv** [comment]
ok, I figured
